### PR TITLE
Adding namespace support

### PR DESCRIPTION
**Pull request by maxfortun**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@maxfortun Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=315)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-vault&pullRequestId=315) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@maxfortun Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=315)!

**Comment by mp911de** [comment]
Please create an issue first so we can discuss how to address this issue before proposing code changes?

**Comment by maxfortun** [comment]
Created an issue #316.

**Comment by mp911de** [comment]
Thank you for submitting a change. We don't want to introduce the concept of namespaces to each authentication mechanism hence we won't merge this PR. Let's keep #316 to track the further activity around namespaces.

**Pull request closed without merging**
