### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by DanielFran** [comment]
@mp911de I updated all dependencies for next release

**Comment by mp911de** [comment]
Thanks for your effort. Typically, we create a ticket for each dependency upgrade to enlist these in the change log. Care to file issues for all changes and reference these (see 1efaea9f4dd6591d35daa27f0655769b6c026119 for further reference)?

**Comment by mp911de** [comment]
No split needed, but each type of dependency upgrade (Spring Data, Spring Framework, Mockito, …) needs a separate ticket. It's mainly about creating dependency upgrade tickets (see this [filter](https://github.com/spring-projects/spring-vault/issues?q=is%3Aissue+is%3Aclosed+label%3A%22type%3A+dependency-upgrade%22)) and referencing the dependency upgrade ticket per commit message.

**Comment by DanielFran** [comment]
@mp911de I created an issue for each commit.

**Comment by mp911de** [comment]
Thanks a lot. The only left thing to do before merging is reworking the commit messages of this PR and mention each ticket accordingly.

As soon as that's done, we can merge this PR.

**Comment by DanielFran** [comment]
@mp911de I think it is done.
Can you confirm?

**Comment by mp911de** [comment]
While we appreciate contributions, dependency upgrades do not seem to be the best category for contributions as they typically come with a lot of noise and probably generate more effort than handling them on our side.

**Comment by mp911de** [comment]
That's merged and polished. Some updates are backported to 2.1.x.

**Pull request closed without merging**
