### PR TITLE
Added debug statement on properties cleanup.

### PR DESCRIPTION
**Pull request by mozaidk**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mozaidk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=602)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-vault&pullRequestId=602) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mozaidk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=602)!

**Comment by mp911de** [comment]
Can you help us understand what you're trying to achieve before actually submitting code changes?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Pull request closed without merging**
