### PR TITLE
Issue#462 : Add support for custom kubernetes auth path

### PR DESCRIPTION
**Pull request by hitenny**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hitenny Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=464)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-vault&pullRequestId=464) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hitenny Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=464)!

**Comment by raoofm** [comment]
@mp911de can this be merged?

**Comment by mp911de** [comment]
The thing that blocks currently the merge is that we would want to apply path customization for all supported authentication mechanisms and we didn't get to work on that yet. Feel free to pick up this PR and extending it.

**Comment by mp911de** [comment]
Superseded by #507.

**Pull request closed without merging**
