### PR TITLE
Correct Javadoc example code for SecretLeaseContainer

### PR DESCRIPTION
**Pull request by mikebell90**
Code example didn't correctly reference the object names.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mikebell90 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=209)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-vault&pullRequestId=209) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mikebell90 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=209)!

**Comment by mikebell90** [comment]
Addresses #207

**Comment by mp911de** [comment]
Thanks a lot. That's merged and backported now.

**Pull request closed without merging**
