### PR TITLE
Upgrade spring to 4.3.20

### PR DESCRIPTION
**Pull request by aj-jaswanth**
@mp911de Could you please review and merge this?

### CODE REVIEW

**Comment by aj-jaswanth** [comment]
Travis build for `springNext` has timed out.

**Comment by mp911de** [comment]
Thanks a lot. We're expecting Spring Framework 4.3.20 by next week so I'd rather keep that one open and upgrade to 4.3.20 once it's available.

**Comment by aj-jaswanth** [comment]
Sure. Thanks.

**Comment by aj-jaswanth** [comment]
@mp911de Upgrade to spring 4.3.20

**Comment by mp911de** [comment]
Thanks a lot. That's merged now.

**Pull request closed without merging**
