### PR TITLE
Migrate AWS EC2 role-id property to role in EnvironmentVaultConfiguration

### LINKED ISSUE #508: Incorrect environment property for aws ec2 role
Incorrect environment property for aws ec2 role specified [here](https://github.com/spring-projects/spring-vault/blob/master/spring-vault-core/src/main/java/org/springframework/vault/config/EnvironmentVaultConfiguration.java#L341)
As of now it is vault.aws-ec2.role-id

As per docs it should be vault.aws-ec2.role

### PR DESCRIPTION
**Pull request by raoofm**
fixes #508

### CODE REVIEW

**Comment by mp911de** [comment]
There's quite some difference between the implementation and the documentation. The PR contains a lot of cleanups and unrelated changes. 

We cannot just change `vault.aws-ec2.role-id` to `vault.aws-ec2.role` as this is a breaking change. Instead, we need to consider both properties. Care to rework your pull request and limit changes only to that particular issue?

**Comment by raoofm** [comment]
@mp911de it got messy while merging, do you want me to open a new one or is this fine?

**Comment by mp911de** [comment]
Instead of merging, please rebase your branch and squash commits. Force-pushing in pull requests is fine as long as we haven’t started yet with an integration.

**Comment by raoofm** [comment]
yeah totally agree, didn't notice that the same file would change in a few hours, knowing commits to this repo to be slow, my bad

**Comment by raoofm** [comment]
@mp911de it's ready now, please review

**Comment by raoofm** [comment]
@mp911de checks passed, ready for review

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.

**Pull request closed without merging**
