### PR TITLE
Adding Transform Secrets Engine support

### PR DESCRIPTION
**Pull request by Valarissa**
This feature is only available if your vault binary is an enterprise version 1.4 or higher.

The feature allows for FPE or just masking out some data. This is useful when sending sensitive information over the wire without requiring a schema change.

You can read more about the API and feature here: https://www.vaultproject.io/docs/secrets/transform
There's also the HTTP API that can be found here: https://www.vaultproject.io/api-docs/secret/transform

Let me know if there's anything else you'd like me to add to this feature support.

We (HashiCorp) are hoping to get this rolled out sooner rather than later, but quality comes before speed. Hopefully, I'll be able to help you all out in getting some of our newer features rolled out in this repo!

Cheers!

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Valarissa Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=570)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-vault&pullRequestId=570) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by mp911de** [comment]
Thanks a lot for submitting a pull request. At first glance, this PR looks pretty decent, I've seen only a few super minor issues (inception year in the license headers should be 2020 only, some `@since` tags on methods that say version 1.1 instead on class level having `@since 2.3`) that we can sort out either during the PR phase or during the merge.

To be able to continue here, you'd need to sign the [contributor license agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=570).

**Comment by Valarissa** [comment]
@mp911de Thanks for the update. I work for HashiCorp, so, there's some issues with me signing the CLA right now. I'll make the changes you requested and wait until we hear back from our legal dept to understand how to move forward with the CLA. (I have every confidence that it will be signed eventually, we're just waiting to see how this works)

**Comment by mp911de** [comment]
Hey there, is there an update regarding the CLA?

**Comment by Valarissa** [comment]
Not as of yet. All of us on the team are getting antsy with how long a resolution is taking :(

**Comment by mp911de** [comment]
Sorry to hear.

**Comment by pivotal-issuemaster** [comment]
@Valarissa Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-vault&pullRequestId=570)!

**Comment by Valarissa** [comment]
@mp911de It turns out HC had signed it previously and the problem was the visibility of my membership with the HashiCorp organization! We should be good to go.

**Comment by mp911de** [comment]
Great to hear. I'm back in September in the office, I'll take care of the merge then.

**Comment by mp911de** [comment]
I had a look at the PR. What about encoding values that return a `generated` `tweak_source`? Right now, the generated `tweak` isn't returned to the caller. 

I prepared the merge already locally, so I can take care of any changes that result out of this discussion.

**Comment by Valarissa** [comment]
Taking a look right now. Thanks for the review.

**Comment by Valarissa** [comment]
So, you're correct that I forgot to include that. I'm thinking of extending the `TransformCiphertext` to accept a `nullable` tweak to be able to receive the tweak value from a `generated` `tweak_source`. Thoughts?

**Comment by mp911de** [comment]
Thanks for having a look. I think we can model it by attaching the tweak to the ciphertext object. Let me apply that change and push all changes onto a branch next week.

**Comment by Valarissa** [comment]
Ok, I just pushed up some changes to always return a TransformCiphertext and modify the context if a tweak is provided, otherwise, the encode request's context is returned as part of the TransformCiphertext.

**Comment by Valarissa** [comment]
Test failures are likely due to the version of java being used to run the tests. As of Vault 1.4.2, an issue was introduced with Java environments where TLS 1.3 is not appropriately implemented for Java 14.x.x. The latest version of Java 11 is implemented correctly and does not have this issue.

**Comment by mp911de** [comment]
Thanks a lot for the detail. I also came across the issue with TLS 1.3 in Java and for now (until the fixed Java version is available in all build environments), we pin the TLS version to 1.2 for our tests.

Thank you for your contribution. That's merged and polished now.

**Comment by mp911de** [comment]
This ticket was the last one that we wanted to include in version 2.3 M1. We can ship 2.3 M1 by mid next week or so.

**Pull request closed without merging**
